name: bionic_tech
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  firebase_core: 2.31.0
  firebase_auth: ^4.19.5
  google_fonts: ^6.2.1
  convex_bottom_bar: 3.2.0
  google_sign_in: 6.2.1
  youtube_player_flutter: 9.0.1
  path_provider: ^2.1.3
  path: ^1.9.0
  geolocator: 11.0.0
  intl: 0.19.0
  cloud_firestore: 4.17.3
  get_storage: 2.1.1
  flutter:
    sdk: flutter
  lottie: ^3.1.1

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
